[package]

name = "xxhash"
description = "The xxHash hashing algorithm"
version = "0.0.8"
authors = ["György Andrasek <jurily@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/Jurily/rust-xxhash"
